// Mappatura nazionalità → codice paese ISO 3166-1 alpha-2
export const nationalityToCountryCode = {
  // Europa
  British: "GB",
  German: "DE",
  Spanish: "ES",
  French: "FR",
  Italian: "IT",
  Dutch: "NL",
  Finnish: "FI",
  Danish: "DK",
  Swedish: "SE",
  Norwegian: "NO",
  Austrian: "AT",
  Swiss: "CH",
  Belgian: "BE",
  Portuguese: "PT",
  Polish: "PL",
  Hungarian: "HU",
  Czech: "CZ",
  Russian: "RU",
  Ukrainian: "UA",
  Greek: "GR",
  Irish: "IE",
  Romanian: "RO",
  Bulgarian: "BG",
  Croatian: "HR",
  Slovenian: "SI",
  Slovak: "SK",
  Estonian: "EE",
  Latvian: "LV",
  Lithuanian: "LT",
  Icelandic: "IS",
  Monegasque: "MC",
  Liechtensteiner: "LI",
  Luxembourgish: "LU",

  // Nord America
  American: "US",
  Canadian: "CA",
  Mexican: "MX",

  // Sud America
  Brazilian: "BR",
  Argentinian: "AR",
  Argentine: "AR",
  Chilean: "CL",
  Colombian: "CO",
  Venezuelan: "VE",
  Uruguayan: "UY",
  Peruvian: "PE",
  Ecuadorian: "EC",

  // Asia
  Japanese: "JP",
  Chinese: "CN",
  Korean: "KR",
  "South Korean": "KR",
  Indian: "IN",
  Thai: "TH",
  Malaysian: "MY",
  Singaporean: "SG",
  Indonesian: "ID",
  Philippine: "PH",
  Vietnamese: "VN",
  Taiwanese: "TW",
  "Hong Kong": "HK",

  // Oceania
  Australian: "AU",
  "New Zealand": "NZ",

  // Africa
  "South African": "ZA",
  Egyptian: "EG",
  Moroccan: "MA",
  Nigerian: "NG",
  Kenyan: "KE",
  Zimbabwean: "ZW",

  // Medio Oriente
  Turkish: "TR",
  Israeli: "IL",
  Lebanese: "LB",
  Iranian: "IR",
  "Saudi Arabian": "SA",
  Emirati: "AE",
  Qatari: "QA",
  Kuwaiti: "KW",
  Bahraini: "BH",
  Jordanian: "JO",
  Iraqi: "IQ",
  Syrian: "SY",
  Omani: "OM",
  Yemeni: "YE",
};
